### PR TITLE
Update code owners to teams

### PR DESCRIPTION
**Pull request by marco-bertschi**
Update code owners to teams for easier maintenance

### CODE REVIEW

**Review by pascalberger — CHANGES_REQUESTED** [review]
Doesn't seem to work like this (see https://github.com/bbtsoftware/BBT.StrategyPattern/pull/36)

**Comment by marco-bertschi** [comment]
> Doesn't seem to work like this (see [bbtsoftware/BBT.StrategyPattern#36](https://github.com/bbtsoftware/BBT.StrategyPattern/pull/36))

I don't get it, [bbtsoftware/BBT.StrategyPattern#36](https://github.com/bbtsoftware/BBT.StrategyPattern/pull/36) is about using `inheritdoc` whereas this PR is about updating the code owners?

**Comment by pascalberger** [comment]
> > Doesn't seem to work like this (see [bbtsoftware/BBT.StrategyPattern#36](https://github.com> 
> I don't get it, [bbtsoftware/BBT.StrategyPattern#36](https://github.com/bbtsoftware/BBT.StrategyPattern/pull/36) is about using `inheritdoc` whereas this PR is about updating the code owners?

https://github.com/bbtsoftware/BBT.StrategyPattern/pull/36 was mainly my test if automatic review request are working, which failed. But in the meantime I set teams to public, which might have been the issue

**Comment by marco-bertschi** [comment]
> > > Doesn't seem to work like this (see [[bbtsoftware/BBT.StrategyPattern#36](https://github.com/bbtsoftware/BBT.StrategyPattern/pull/36)]([https://github.com>](https://github.com%3E)
> > > I don't get it, [bbtsoftware/BBT.StrategyPattern#36](https://github.com/bbtsoftware/BBT.StrategyPattern/pull/36) is about using `inheritdoc` whereas this PR is about updating the code owners?
> 
> [bbtsoftware/BBT.StrategyPattern#36](https://github.com/bbtsoftware/BBT.StrategyPattern/pull/36) was mainly my test if automatic review request are working, which failed. But in the meantime I set teams to public, which might have been the issue

Ah I see.

**Comment by pascalberger** [comment]
> 
> 
> > > Doesn't seem to work like this (see [[bbtsoftware/BBT.StrategyPattern#36](https://github.com/bbtsoftware/BBT.StrategyPattern/pull/36)]([https://github.com>](https://github.com%3E)
> > > I don't get it, [bbtsoftware/BBT.StrategyPattern#36](https://github.com/bbtsoftware/BBT.StrategyPattern/pull/36) is about using `inheritdoc` whereas this PR is about updating the code owners?
> 
> [bbtsoftware/BBT.StrategyPattern#36](https://github.com/bbtsoftware/BBT.StrategyPattern/pull/36) was mainly my test if automatic review request are working, which failed. But in the meantime I set teams to public, which might have been the issue

Nope, still not working (https://github.com/bbtsoftware/BBT.StrategyPattern/pull/38)

**Comment by marco-bertschi** [comment]
Alright, abandoning this in favour of a working solution then?

**Review by pascalberger — APPROVED** [review]
I made the required changes to the team settings so that this should work now

**Pull request merged**
